### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [greydot/aeson-iproute#4]
```
aeson-iproute                  > Building library for aeson-iproute-0.2.1..
aeson-iproute                  > [1 of 1] Compiling Data.Aeson.IP
aeson-iproute                  >           
aeson-iproute                  > /tmp/stack-8cc6eb7a97cc4e67/aeson-iproute-0.2.1/Data/Aeson/IP.hs:124:13: error:
aeson-iproute                  >     • Couldn't match type: HashMap.HashMap Text.Text Value
aeson-iproute                  >                      with: Data.Aeson.KeyMap.KeyMap Value
aeson-iproute                  >       Expected: Object -> Parser (IPRTable k a)
aeson-iproute                  >         Actual: HashMap.HashMap Text.Text Value -> Parser (IPRTable k a)
aeson-iproute                  >     • In the second argument of ‘($)’, namely
aeson-iproute                  >         ‘HashMap.foldrWithKey
aeson-iproute                  >            (\ k v rt
aeson-iproute                  >               -> RouteTable.insert <$> f k <?> Key k <*> p v <?> Key k <*> rt)
aeson-iproute                  >            (pure RouteTable.empty)’
aeson-iproute                  >       In the expression:
aeson-iproute                  >         withObject "IPRTable k v"
aeson-iproute                  >           $ HashMap.foldrWithKey
aeson-iproute                  >               (\ k v rt
aeson-iproute                  >                  -> RouteTable.insert <$> f k <?> Key k <*> p v <?> Key k <*> rt)
aeson-iproute                  >               (pure RouteTable.empty)
aeson-iproute                  >       In a case alternative:
aeson-iproute                  >           FromJSONKeyTextParser f
aeson-iproute                  >             -> withObject "IPRTable k v"
aeson-iproute                  >                  $ HashMap.foldrWithKey
aeson-iproute                  >                      (\ k v rt
aeson-iproute                  >                         -> RouteTable.insert <$> f k <?> Key k <*> p v <?> Key k <*> rt)
aeson-iproute                  >                      (pure RouteTable.empty)
aeson-iproute                  >     |     
aeson-iproute                  > 124 |             HashMap.foldrWithKey
aeson-iproute                  >     |             ^^^^^^^^^^^^^^^^^^^^...
aeson-iproute                  >           
aeson-iproute                  > /tmp/stack-8cc6eb7a97cc4e67/aeson-iproute-0.2.1/Data/Aeson/IP.hs:125:63: error:
aeson-iproute                  >     • Couldn't match expected type ‘Key’ with actual type ‘Text.Text’
aeson-iproute                  >     • In the first argument of ‘Key’, namely ‘k’
aeson-iproute                  >       In the second argument of ‘(<?>)’, namely ‘Key k’
aeson-iproute                  >       In the second argument of ‘(<$>)’, namely ‘f k <?> Key k’
aeson-iproute                  >     |     
aeson-iproute                  > 125 |                 (\k v rt -> RouteTable.insert <$> f k <?> Key k
aeson-iproute                  >     |                                                               ^
aeson-iproute                  >           
aeson-iproute                  > /tmp/stack-8cc6eb7a97cc4e67/aeson-iproute-0.2.1/Data/Aeson/IP.hs:126:63: error:
aeson-iproute                  >     • Couldn't match expected type ‘Key’ with actual type ‘Text.Text’
aeson-iproute                  >     • In the first argument of ‘Key’, namely ‘k’
aeson-iproute                  >       In the second argument of ‘(<?>)’, namely ‘Key k’
aeson-iproute                  >       In the second argument of ‘(<*>)’, namely ‘p v <?> Key k’
aeson-iproute                  >     |     
aeson-iproute                  > 126 |                                               <*> p v <?> Key k
aeson-iproute                  >     |                                                               ^
aeson-iproute                  >           
aeson-iproute                  > /tmp/stack-8cc6eb7a97cc4e67/aeson-iproute-0.2.1/Data/Aeson/IP.hs:140:39: error:
aeson-iproute                  >     • Couldn't match type: HashMap.HashMap Key Value
aeson-iproute                  >                      with: Data.Aeson.KeyMap.KeyMap Value
aeson-iproute                  >       Expected: IPRTable k a -> Object
aeson-iproute                  >         Actual: IPRTable k a -> HashMap.HashMap Key Value
aeson-iproute                  >     • In the second argument of ‘(.)’, namely
aeson-iproute                  >         ‘HashMap.fromList
aeson-iproute                  >            . map (\ (k, v) -> (f k, g v)) . RouteTable.toList’
aeson-iproute                  >       In the expression:
aeson-iproute                  >         Object
aeson-iproute                  >           . HashMap.fromList
aeson-iproute                  >               . map (\ (k, v) -> (f k, g v)) . RouteTable.toList
aeson-iproute                  >       In a case alternative:
aeson-iproute                  >           ToJSONKeyText f _
aeson-iproute                  >             -> Object
aeson-iproute                  >                  . HashMap.fromList
aeson-iproute                  >                      . map (\ (k, v) -> (f k, g v)) . RouteTable.toList
aeson-iproute                  >     |     
aeson-iproute                  > 140 |         ToJSONKeyText f _ -> Object . HashMap.fromList
aeson-iproute                  >     |                                       ^^^^^^^^^^^^^^^^...
```

**Comment by greydot** [comment]
Thank you for your report!

I fixed it here: https://github.com/greydot/aeson-iproute/pull/5

I'll drop in this version in some of my code to test for regressions and will release a new version in the coming days.
